# Generated by Django 2.2.7 on 2020-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Category',
            field=models.CharField(default='Chairman', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Course',
            field=models.CharField(default='M & I', max_length=50),
        ),
    ]
