# Generated by Django 2.2.7 on 2020-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'Female')], default='male', max_length=5),
        ),
    ]
