# Generated by Django 2.2.7 on 2020-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20200201_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='YearSem',
            field=models.CharField(choices=[('1.1', 'Y1S1'), ('1.2', 'Y1S2'), ('2.1', 'Y2S1'), ('2.2', 'Y2S2'), ('3', 'Y3S1'), ('3', 'Y3S2'), ('4', 'Y4S1'), ('4', 'Y4S2')], max_length=4),
        ),
    ]
