# Generated by Django 2.2.7 on 2020-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20200205_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Category',
            field=models.CharField(choices=[('c', 'chairman'), ('s', 'secretary'), ('e', 'Entertainment'), ('t', 'Treasurer'), ('a', 'Academic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Gender',
            field=models.TextField(choices=[('m', 'male'), ('f', 'Female')], default='male', max_length=5),
        ),
    ]
