# Generated by Django 2.2.7 on 2020-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Category',
            field=models.CharField(choices=[('chairman', 'chairman'), ('secretary', 'secretary'), ('Entertainment', 'Entertainment'), ('Treasurer', 'Treasurer'), ('Academic', 'Academic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Academic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Entertainment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Treasurer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='chairman',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vote',
            name='secretary',
            field=models.CharField(default='', max_length=50),
        ),
    ]
