# Generated by Django 2.2.7 on 2020-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20200205_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='User',
            field=models.DecimalField(decimal_places=0, max_digits=24),
        ),
    ]
