# Generated by Django 2.2.7 on 2020-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0018_auto_20200205_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Category',
            field=models.CharField(choices=[('chairman', 'chairman'), ('secretary', 'secretary'), ('Entertainment', 'Entertainment'), ('Treasurer', 'Treasurer'), ('Academic', 'Academic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Gender',
            field=models.TextField(choices=[('m', 'male'), ('f', 'Female')], default='male', max_length=5),
        ),
    ]
