# Generated by Django 2.2.7 on 2020-02-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0020_auto_20200205_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='YearSem',
            field=models.CharField(choices=[('Y1S1', 'Y1S1'), ('Y1S2', 'Y1S2'), ('Y2S1', 'Y2S1'), ('Y2S2', 'Y2S2'), ('Y3S1', 'Y3S1'), ('Y3S2', 'Y3S2'), ('Y4S1', 'Y4S1'), ('Y4S2', 'Y4S2')], max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
